runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "blogapp_yuqi"

handlers:
- url: /
  static_files: dist/project/index.html
  upload: dist/project/index.html

- url: /
  static_dir: dist/project